name: publish docs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  deploy:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build website
        run: |
          nix build .#
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
